Repository pond/scimitar, pull requests merged in 2021-03, with the labels that each got.

#2 Add source code link to gemspec file
  CHANGELOG.md
  lib/scimitar/version.rb
  scimitar.gemspec
Labels: bug

#3 Add Travis for CI
  .travis.yml
  CHANGELOG.md
  Gemfile.lock
  README.md
  lib/scimitar/version.rb
  scimitar.gemspec
Labels: enhancement

#4 More robust PATCH patch filter parsing
  CHANGELOG.md
  Gemfile.lock
  app/models/scimitar/resources/mixin.rb
  lib/scimitar/version.rb
  spec/models/scimitar/resources/mixin_spec.rb
Labels: enhancement

#5 Update README.md
  README.md
Labels: documentation
