Repository pond/scimitar, pull requests merged in 2022-07, with the labels that each got.

#17 Add detail to some FilterErrors
  app/models/scimitar/lists/query_parser.rb
Labels: enhancement

#26 v2.1.0
  .ruby-version
  CHANGELOG.md
  Gemfile.lock
  README.md
  app/controllers/scimitar/application_controller.rb
  app/models/scimitar/engine_configuration.rb
  app/models/scimitar/error_response.rb
  config/initializers/scimitar.rb
  lib/scimitar/version.rb
  spec/controllers/scimitar/application_controller_spec.rb
  spec/models/scimitar/complex_types/email_spec.rb
  spec/models/scimitar/resources/base_validation_spec.rb
  spec/models/scimitar/schema/base_spec.rb
  spec/models/scimitar/schema/user_spec.rb
Labels: enhancement, maintenance

#27 Back-port v2.1 features to v1.3 for Rails 6 users
  CHANGELOG.md
  Gemfile.lock
  README.md
  app/controllers/scimitar/application_controller.rb
  app/models/scimitar/engine_configuration.rb
  app/models/scimitar/error_response.rb
  app/models/scimitar/lists/query_parser.rb
  app/models/scimitar/schema/address.rb
  app/models/scimitar/schema/vdtp.rb
  config/initializers/scimitar.rb
  lib/scimitar/version.rb
  spec/controllers/scimitar/application_controller_spec.rb
  spec/models/scimitar/complex_types/email_spec.rb
  spec/models/scimitar/resources/base_validation_spec.rb
  spec/models/scimitar/schema/base_spec.rb
  spec/models/scimitar/schema/user_spec.rb
Labels: maintenance

#28 Sync with v1.3
  CHANGELOG.md
  app/controllers/scimitar/application_controller.rb
  app/models/scimitar/error_response.rb
  spec/controllers/scimitar/application_controller_spec.rb
Labels: maintenance
